import { IShipment, Status } from "./Interfaces";

export const shipments: IShipment[] = [
  {
    id: "1",
    carrier: "DHL",
    trackingCode: "DHL123456789",
    carrierTrackingUrl: "http://dhl.com/track?code=DHL123456789",
    trackingDate: new Date("2023-05-01"),
    status: Status.inProcess,
    statusChangeDate: new Date("2023-05-02"),
    statusChangeReason: "Package received at sorting center",
    weight: 2.5,
    estimatedDeliveryDate: new Date("2023-05-05"),
    addressFrom: {
      id: "A1",
      streetNr: "123",
      streetName: "Main St",
      streetSuffix: "Apt 4",
      postcode: "10001",
      city: "New York",
      country: "USA",
    },
    addressTo: {
      id: "A2",
      streetNr: "456",
      streetName: "Broadway",
      streetSuffix: "Suite 1",
      postcode: "90001",
      city: "Los Angeles",
      country: "USA",
    },
    order: {
      id: "O1",
      href: "http://example.com/order/1",
      name: "Order 1",
      referredType: "Online",
    },
    relatedCustomer: {
      id: "C1",
      href: "http://example.com/customer/1",
      name: "John Doe",
      description: "Regular customer",
    },
    createDate: new Date("2023-04-30"),
  },
  {
    id: "2",
    carrier: "FedEx",
    trackingCode: "FED123456789",
    carrierTrackingUrl: "http://fedex.com/track?code=FED123456789",
    trackingDate: new Date("2023-05-02"),
    status: Status.shipped,
    statusChangeDate: new Date("2023-05-03"),
    statusChangeReason: "Package in transit",
    weight: 1.2,
    estimatedDeliveryDate: new Date("2023-05-06"),
    addressFrom: {
      id: "A3",
      streetNr: "789",
      streetName: "Elm St",
      streetSuffix: "",
      postcode: "20002",
      city: "Washington",
      country: "USA",
    },
    addressTo: {
      id: "A4",
      streetNr: "321",
      streetName: "Market St",
      streetSuffix: "Floor 5",
      postcode: "94103",
      city: "San Francisco",
      country: "USA",
    },
    order: {
      id: "O2",
      href: "http://example.com/order/2",
      name: "Order 2",
      referredType: "Retail",
    },
    relatedCustomer: {
      id: "C2",
      href: "http://example.com/customer/2",
      name: "Jane Smith",
      description: "New customer",
    },
    createDate: new Date("2023-05-01"),
  },
  {
    id: "3",
    carrier: "UPS",
    trackingCode: "UPS123456789",
    carrierTrackingUrl: "http://ups.com/track?code=UPS123456789",
    trackingDate: new Date("2023-05-03"),
    status: Status.delivered,
    statusChangeDate: new Date("2023-05-05"),
    statusChangeReason: "Package delivered",
    weight: 3.0,
    estimatedDeliveryDate: new Date("2023-05-07"),
    addressFrom: {
      id: "A5",
      streetNr: "555",
      streetName: "Oak St",
      streetSuffix: "Ste 10",
      postcode: "60601",
      city: "Chicago",
      country: "USA",
    },
    addressTo: {
      id: "A6",
      streetNr: "777",
      streetName: "Pine St",
      streetSuffix: "",
      postcode: "98101",
      city: "Seattle",
      country: "USA",
    },
    order: {
      id: "O3",
      href: "http://example.com/order/3",
      name: "Order 3",
      referredType: "Wholesale",
    },
    relatedCustomer: {
      id: "C3",
      href: "http://example.com/customer/3",
      name: "Alice Johnson",
      description: "Frequent buyer",
    },
    createDate: new Date("2023-05-02"),
  },
  {
    id: "4",
    carrier: "USPS",
    trackingCode: "USPS123456789",
    carrierTrackingUrl: "http://usps.com/track?code=USPS123456789",
    trackingDate: new Date("2023-05-04"),
    status: Status.initialized,
    statusChangeDate: new Date("2023-05-04"),
    statusChangeReason: "Label created",
    weight: 0.5,
    estimatedDeliveryDate: new Date("2023-05-08"),
    addressFrom: {
      id: "A7",
      streetNr: "888",
      streetName: "Birch St",
      streetSuffix: "Unit 2",
      postcode: "30301",
      city: "Atlanta",
      country: "USA",
    },
    addressTo: {
      id: "A8",
      streetNr: "999",
      streetName: "Cedar St",
      streetSuffix: "",
      postcode: "33101",
      city: "Miami",
      country: "USA",
    },
    order: {
      id: "O4",
      href: "http://example.com/order/4",
      name: "Order 4",
      referredType: "Dropship",
    },
    relatedCustomer: {
      id: "C4",
      href: "http://example.com/customer/4",
      name: "Bob Brown",
      description: "Occasional buyer",
    },
    createDate: new Date("2023-05-03"),
  },
  {
    id: "5",
    carrier: "DHL",
    trackingCode: "DHL987654321",
    carrierTrackingUrl: "http://dhl.com/track?code=DHL987654321",
    trackingDate: new Date("2023-05-05"),
    status: Status.returned,
    statusChangeDate: new Date("2023-05-07"),
    statusChangeReason: "Package returned to sender",
    weight: 4.0,
    estimatedDeliveryDate: new Date("2023-05-09"),
    addressFrom: {
      id: "A9",
      streetNr: "111",
      streetName: "Maple St",
      streetSuffix: "Apt 3",
      postcode: "75201",
      city: "Dallas",
      country: "USA",
    },
    addressTo: {
      id: "A10",
      streetNr: "222",
      streetName: "Spruce St",
      streetSuffix: "Bldg B",
      postcode: "48201",
      city: "Detroit",
      country: "USA",
    },
    order: {
      id: "O5",
      href: "http://example.com/order/5",
      name: "Order 5",
      referredType: "E-commerce",
    },
    relatedCustomer: {
      id: "C5",
      href: "http://example.com/customer/5",
      name: "Charlie Green",
      description: "One-time purchase",
    },
    createDate: new Date("2023-05-04"),
  },
  {
    id: "6",
    carrier: "FedEx",
    trackingCode: "FED987654321",
    carrierTrackingUrl: "http://fedex.com/track?code=FED987654321",
    trackingDate: new Date("2023-05-06"),
    status: Status.inCustoms,
    statusChangeDate: new Date("2023-05-07"),
    statusChangeReason: "Held at customs",
    weight: 1.8,
    estimatedDeliveryDate: new Date("2023-05-10"),
    addressFrom: {
      id: "A11",
      streetNr: "333",
      streetName: "Willow St",
      streetSuffix: "Unit 5",
      postcode: "94101",
      city: "San Francisco",
      country: "USA",
    },
    addressTo: {
      id: "A12",
      streetNr: "444",
      streetName: "Ash St",
      streetSuffix: "Floor 2",
      postcode: "10002",
      city: "New York",
      country: "USA",
    },
    order: {
      id: "O6",
      href: "http://example.com/order/6",
      name: "Order 6",
      referredType: "Subscription",
    },
    relatedCustomer: {
      id: "C6",
      href: "http://example.com/customer/6",
      name: "Daisy White",
      description: "Subscriber",
    },
    createDate: new Date("2023-05-05"),
  },
  {
    id: "7",
    carrier: "UPS",
    trackingCode: "UPS987654321",
    carrierTrackingUrl: "http://ups.com/track?code=UPS987654321",
    trackingDate: new Date("2023-05-07"),
    status: Status.error,
    statusChangeDate: new Date("2023-05-08"),
    statusChangeReason: "Incorrect address",
    weight: 2.2,
    estimatedDeliveryDate: new Date("2023-05-11"),
    addressFrom: {
      id: "A13",
      streetNr: "555",
      streetName: "Chestnut St",
      streetSuffix: "Suite 7",
      postcode: "60601",
      city: "Chicago",
      country: "USA",
    },
    addressTo: {
      id: "A14",
      streetNr: "666",
      streetName: "Beech St",
      streetSuffix: "Apt 8",
      postcode: "98102",
      city: "Seattle",
      country: "USA",
    },
    order: {
      id: "O7",
      href: "http://example.com/order/7",
      name: "Order 7",
      referredType: "Gift",
    },
    relatedCustomer: {
      id: "C7",
      href: "http://example.com/customer/7",
      name: "Eve Black",
      description: "Gift recipient",
    },
    createDate: new Date("2023-05-06"),
  },
  {
    id: "8",
    carrier: "USPS",
    trackingCode: "USPS987654321",
    carrierTrackingUrl: "http://usps.com/track?code=USPS987654321",
    trackingDate: new Date("2023-05-08"),
    status: Status.processed,
    statusChangeDate: new Date("2023-05-09"),
    statusChangeReason: "Processed at facility",
    weight: 0.9,
    estimatedDeliveryDate: new Date("2023-05-12"),
    addressFrom: {
      id: "A15",
      streetNr: "777",
      streetName: "Hickory St",
      streetSuffix: "Suite 9",
      postcode: "30302",
      city: "Atlanta",
      country: "USA",
    },
    addressTo: {
      id: "A16",
      streetNr: "888",
      streetName: "Fir St",
      streetSuffix: "Unit 10",
      postcode: "33102",
      city: "Miami",
      country: "USA",
    },
    order: {
      id: "O8",
      href: "http://example.com/order/8",
      name: "Order 8",
      referredType: "Corporate",
    },
    relatedCustomer: {
      id: "C8",
      href: "http://example.com/customer/8",
      name: "Frank Gray",
      description: "Corporate client",
    },
    createDate: new Date("2023-05-07"),
  },
  {
    id: "9",
    carrier: "DHL",
    trackingCode: "DHL1122334455",
    carrierTrackingUrl: "http://dhl.com/track?code=DHL1122334455",
    trackingDate: new Date("2023-05-09"),
    status: Status.inProcess,
    statusChangeDate: new Date("2023-05-10"),
    statusChangeReason: "Package being prepared",
    weight: 3.5,
    estimatedDeliveryDate: new Date("2023-05-13"),
    addressFrom: {
      id: "A17",
      streetNr: "999",
      streetName: "Maple St",
      streetSuffix: "Unit 11",
      postcode: "75202",
      city: "Dallas",
      country: "USA",
    },
    addressTo: {
      id: "A18",
      streetNr: "111",
      streetName: "Poplar St",
      streetSuffix: "Ste 12",
      postcode: "48202",
      city: "Detroit",
      country: "USA",
    },
    order: {
      id: "O9",
      href: "http://example.com/order/9",
      name: "Order 9",
      referredType: "International",
    },
    relatedCustomer: {
      id: "C9",
      href: "http://example.com/customer/9",
      name: "Grace Silver",
      description: "International customer",
    },
    createDate: new Date("2023-05-08"),
  },
  {
    id: "10",
    carrier: "FedEx",
    trackingCode: "FED1122334455",
    carrierTrackingUrl: "http://fedex.com/track?code=FED1122334455",
    trackingDate: new Date("2023-05-10"),
    status: Status.shipped,
    statusChangeDate: new Date("2023-05-11"),
    statusChangeReason: "Package shipped",
    weight: 2.1,
    estimatedDeliveryDate: new Date("2023-05-14"),
    addressFrom: {
      id: "A19",
      streetNr: "222",
      streetName: "Elm St",
      streetSuffix: "Apt 13",
      postcode: "94102",
      city: "San Francisco",
      country: "USA",
    },
    addressTo: {
      id: "A20",
      streetNr: "333",
      streetName: "Pine St",
      streetSuffix: "Floor 14",
      postcode: "10003",
      city: "New York",
      country: "USA",
    },
    order: {
      id: "O10",
      href: "http://example.com/order/10",
      name: "Order 10",
      referredType: "Bulk",
    },
    relatedCustomer: {
      id: "C10",
      href: "http://example.com/customer/10",
      name: "Hank Gold",
      description: "Bulk buyer",
    },
    createDate: new Date("2023-05-09"),
  },
];
